### ISSUE TITLE
Swift 3.0 support

### ISSUE THREAD

**Issue by SentoCrespo** [XWebView/XWebView#54]
Is it planned or already released? I can't find it.

Thanks!

**Comment by andriyslyusar** [comment]
I have the same question?

**Comment by SentoCrespo** [comment]
I tried your branch with CocoaPods but it's failing to compile in Xcode 8.0. Anything special to do there?

Thanks man!

**Comment by SentoCrespo** [comment]
Further info. I have this in post_install so many pods compile

```
installer.pods_project.targets.each do |target|

        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
        end

    end
```

I've tried to include it with Carthage like:

```
github "andreyslyusar/XWebView" "feature/swift-2.3"
```

And it fails to compile:

```
XWVHttpServer.swift:185:76: error: cannot force unwrap value of non-optional type 'NSURL'
XWebView.swift:126:54: error: cannot force unwrap value of non-optional type 'String'
```

**Comment by andriyslyusar** [comment]
It is not possible to mix swift 2.3 and swift 3.0 in the same project. Here is an example of my working pod file.

```
use_frameworks!
platform :ios, '9.0'

target 'SWWebContentKit' do
  pod 'SnapKit', '~> 0.22.0'
  pod 'DZNWebViewController', '~> 3.1'

  pod 'XWebView',
    :git => 'https://github.com/andreyslyusar/XWebView.git',
    :branch => 'feature/swift-2.3'    

  target 'SWWebContentKitTests' do
    inherit! :search_paths
  end

  post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '2.3'
        end
      end
  end  
end
```

I am planning today to finish with fixes to Swift 2.3, make it compatible with Swift 2.2 and create a pull request.

As for swift 3.0 I make an attempt to convert it, but it is >100 mistakes in code. Some of them easy to fix, but C related code changed a lot with https://github.com/apple/swift-evolution/blob/master/proposals/0107-unsaferawpointer.md. Without knowing "area of ​​expertise" it  will be not a trivial task.

**Comment by andriyslyusar** [comment]
Submit #55

**Comment by xwv** [comment]
Thank @andreyslyusar, I just merged the PR #55.

I'll find some spare time to work on Swift 3.0 support.

**Comment by SentoCrespo** [comment]
That would be wonderful. Thanks a lot for your effort!

**Comment by andriyslyusar** [comment]
@xwv I can push my swift 3.0 branch. I have fixed some issues. I can go ahead with general swift changes, but C and pointers nothing I can fix without spending a lot of time.

**Comment by andriyslyusar** [comment]
@xwv Can you please push 0.10 to cocoapods repo, so I can update my private repo podspecs with new dependency.

**Comment by xwv** [comment]
@andreyslyusar , 0.10 had pushed to cocoapods.

For swift 3.0 changes, you can push to the branch swift-3.0.

**Comment by SentoCrespo** [comment]
That would be really awesome. Swift 3.0 is super needed in the project I'm starting.

Thanks for the effort!!!

**Comment by SentoCrespo** [comment]
Hello guys, is Swift 3.0 branch compiling/working for you?

Thanks!

**Comment by SentoCrespo** [comment]
Hello there, any news on this? This is keeping me from migrating a whole project to Swift 3 because of this dependency and I'd really love to continue using it.

Thanks once again!

**Comment by xwv** [comment]
@vCrespoP , sorry for late reply, because I just came back from traveling yesterday.

The Swift 3.0 migration is tough than my imagination. It really changes a lot. A good news is that I have got some progress on dynamic invocation (XWVInvocation.swift), which is the key portion of the project.

**Comment by SentoCrespo** [comment]
Cool!! Keep it up!! I'm eager to use it when it's ready :D

**Comment by barth-zalewski** [comment]
@xwv how is it going? Any news on XWebView with Swift 3?

**Comment by SentoCrespo** [comment]
Yeah, update us, we're thrilling to have it :D

**Comment by xwv** [comment]
@barth-zalewski @vCrespoP , I am sorry to have kept you guys waiting for so long.

I'm working on Swift 3 updating, but I only have 1 or 2 hours per day in average for the work. I had left the project for several months before. You know, during this period, the Swift language and SDK accumulated a lot of changes. Sometimes I felt I was rewriting.

Currently, most of compiling errors are resolved. I estimate 30% - 50% in progress. So, I'm afraid I need another 2 weeks for the first workable version with some features (httpd and ios8 support at least) disabled. And it will require Xcode 8.1 to build. I'll push the code when it is buildable.

**Comment by fernandodev** [comment]
Hello guys,

Unfortunately, I'm in the same situation. Some months ago I had to change to another project and I couldn't pay support to XWebView because I'm not using on that. 

I kindly ask for new contributors and PR's, if you have any improvement, please make smalls PR's that could be easily reviewed and I really would appreciate that.

Thank you

**Comment by SentoCrespo** [comment]
Let's hope  for David @xwv to be able to achieve the goal. 1-2 weeks sounds completely reasonable.

**Comment by xwv** [comment]
Guys, the update for Swift 3.0 was pushed to swift-3.0 branch. All unit tests are passed on my local machine. Please test the experimental change with your apps and feedback the result and issues. Thanks!

**Comment by SentoCrespo** [comment]
Yessssss, you're the man! Will try very very soon. Thanks!

**Comment by ajwhiteway** [comment]
Just a heads up, Float80 is only on OSX so if you are making an iOS app, you'll need to comment out the 3 instances it is referenced.

**Comment by xwv** [comment]
@ajwhiteway , you're right, thanks. I'll remove it or ifdef it.
BTW, beside OS X, it's also available in simulator. That's why I didn't notice.

**Comment by ajwhiteway** [comment]
No problem! I was actually going on the thread to offer to lend a hand in the conversion before I noticed you had actually finished it! Well done!

**Comment by xwv** [comment]
I pushed the final change to master branch. I'll release a new version for this to cocoapods soon.
For swift 2.3 support, checkout the swift-2.3 branch please.
Thanks everyone for your support.

**Comment by SentoCrespo** [comment]
Sorry to come back to this. Amazing job!

Two things:

1)

I've tried without success getting the 0.11.0 version with Carthage and CocoaPods without success. Is the tag in there?

But I've found that using:

```
pod 'XWebView',
            :git => 'https://github.com/XWebView/XWebView.git',
            :branch => 'master'
```

seems to install 0.11.0 version. I'd like to use Carthage but I can live with this :)

2)

I haven't touched my code, and I'm getting this error:

```
webView?.loadPlugin(self, namespace: "myNameSpace")
```

Internally calls:

```
@discardableResult public func loadPlugin(_ object: AnyObject, namespace: String) -> XWVScriptObject? {
        let channel = XWVChannel(webView: self)
        return channel.bindPlugin(object, toNamespace: namespace)
}
```

And that last line is returning the log error:

```
Unsupported type MainWebView
```

Being MainWebView my class, the same that an instance is calling loadPlugin.

Any suggestions?

Thanks a lot once more!

**Comment by andriyslyusar** [comment]
@xwv @vCrespoP 
Thanks a lot for update. 

I try latest from master and find that `loadFileURL:overlayURLs` from "XWebView.swift", all "XWVHttpServer.swift", "XWVHttpConnection.swift" are comment out. Is current master version the latest? It seems to me it should be some mistake here.

**Comment by SentoCrespo** [comment]
I tried using Carthage without success, then CocoaPods but had trouble with them all.

This is my podfile:

```
pod 'XWebView',
            :git => 'https://github.com/XWebView/XWebView.git',
            :branch => 'master'
```

Any advice for Carthage? Any modification needed for the pod? Should I download the project or they have some trouble with dependency managers?

**Comment by SentoCrespo** [comment]
More info for this, when I try using Carthage:

```
# JS Web View
    github "XWebView/XWebView" "master"
```

```
carthage update XWebView --platform iOS
```

```
The following build commands failed:
    CompileSwift normal arm64
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

Warnings:

```
.../XWVObject.swift:74:33: warning: expression implicitly coerced from 'Any?' to Any
.../XWVObject.swift:81:33: warning: expression implicitly coerced from 'Any?' to Any  
.../XWVObject.swift:94:54: warning: expression implicitly coerced from 'Any?' to Any
.../XWVObject.swift:74:33: warning: expression implicitly coerced from 'Any?' to Any
.../XWVObject.swift:81:33: warning: expression implicitly coerced from 'Any?' to Any
.../XWVObject.swift:94:54: warning: expression implicitly coerced from 'Any?' to Any
```

Error:

```
.../XWebViewTests/XWVMetaObjectTest.swift:18:18: error: module 'XWebView' was not compiled for testing
```

For the record, if I tri using the stated version in the readme like:

```
# JS Web View
    github "XWebView/XWebView" ~> 0.11
```

Then I get an error, maybe is because the commit is not tagged with the version?

```
No available version for github "XWebView/XWebView" satisfies the requirement: ~> 0.11.0
```

With CocaPods is exactly the same error:

```
pod 'XWebView', '~> 0.11'

None of your spec sources contain a spec satisfying the dependency: `XWebView (~> 0.11)`.
```

Btw: Doesn't matter if I try 0.11 or 0.11.0.

Thanks a lot for your time and effort!

**Comment by xwv** [comment]
@andreyslyusar , the overlay support is disabled in the first patch of swift 3.0 migration, because I want to submit the patch ASAP. I'm working on the feature, but it's still not ready. That why I have not make a release on cocoapods.

@vCrespoP , you can ignore the error "Unsupported type" if the app doesn't crash.
I think it is not ready to release to CocoaPods. Have you tried to use submodule or directly embed the source of XWebView? Does it work?

**Comment by SentoCrespo** [comment]
The app doesn't crash, but the thing is that the bridging between JS ~> Native is broken. I cannot get any call in my native methods that worked before with Swift 2.2 
:(

**Comment by buscarini** [comment]
Same thing here. It doesn't crash but it doesn't work either

**Comment by SentoCrespo** [comment]
Pull request #61 performed by @buscarini fixes everything. The problem happened for:
- Not defining variables like _variable (Should be documented somewhere though)
- Dictionaries and arrays were not being transformed to JSON

**Comment by xwv** [comment]
@andreyslyusar , the overlay support is ready now, please test. Thanks.
